version: '3.8'
services:
  mysqlserver:
    image: mysql/mysql-server:latest
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=jmvnd
  jmvnd-ui:
    image: liyibo888/jmvnd-ui:v1.3
  jmvnd:
    image: liyibo888/jmvnd:v1.6
    environment:
      - TZ=Asia/Shanghai
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
